services:
  - type: web
    name: betting-analytics-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
  - type: static
    name: betting-analytics-frontend
    staticPublishPath: ./frontend
    buildCommand: echo "No build needed"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
